[settings]
loadout_file = "./appearance.toml"
name = "Element"
run_command = "python ./bot.py"
run_command_linux = "python3 ./bot.py"
agent_id = "Rangler/Element"

[details]
developer = "Rangler"
description = "A neural network trained with reinforcement learning to play 1v1."
fun_fact = "Element was trained with RLGym and has played more than 27 years of Rocket League!"
github = "https://github.com/RLGym/RLGymExampleBot"
language = "rlgym"
tags = [ "1v1",]
